#ifndef __KrzyweLissajousaMyFrame1__
#define __KrzyweLissajousaMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
// tutaj wpisujemy includy
#include <wx/dcclient.h>
#include "Matrix4d.h"
#include "Vector4d.h"

/** Implementing MyFrame1 */
class KrzyweLissajousaMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void drawingPanel_onPaint( wxPaintEvent& event );
		void rotationX_Update( wxScrollEvent& event );
		void rotationY_Update( wxScrollEvent& event );
		void rotationZ_Update( wxScrollEvent& event );
		void sposobRysowania_update( wxCommandEvent& event );
		void coordinates_update( wxCommandEvent& event );
		void A_update( wxScrollEvent& event );
		void a_update( wxScrollEvent& event );
		void f_a_update( wxScrollEvent& event );
		void B_update( wxScrollEvent& event );
		void b_update( wxScrollEvent& event );
		void f_b_update( wxScrollEvent& event );
		void C_update( wxScrollEvent& event );
		void c_update( wxScrollEvent& event );
		void f_c_update( wxScrollEvent& event );
	public:
		/** Constructor */
		KrzyweLissajousaMyFrame1( wxWindow* parent );
	//// end generated class members
	// tutaj wpisujemy metody, zmienne, itp.

	private:
		/** Zmienna(bool) wskazująca które współrzędne zostały wybrane przez użytkownika.
		* == false(0) współrzędne (x,y,z)
		* == true(1) współrzędne (r,theta,phi)
		*/
		bool _coordinates;

		/** Zmienna(bool) wskazujłca sposób rysowania krzywych Lissajousa
		* == false(0) punkty
		* == true(1) odcinki
		*/
		bool _drawingMethod;
		int _angleX;	/** Kąt obrotu wykresu względem osi OX */
		int _angleY;	/** Kąt obrotu wykresu względem osi OY */
		int _angleZ;		/** Kąt obrotu wykresu względem osi OZ */

		double _ampX;	/** Amplituda funkcji x(t)*/
		double _ampY;	/** Amplituda funkcji y(t)*/
		double _ampZ;	/** Amplituda funkcji z(t)*/
		int _aX;	/** a funkcji x(t)*/
		int _bY;	/** b funkcji y(t)*/
		int _cZ;	/** c funkcji z(t)*/
		double _shiftX;	/** przesunięcie funkcji x(t) */
		double _shiftY;	/** przesunięcie funkcji y(t) */
		double _shiftZ;	/** przesunięcie funkcji z(t) */



};

#endif // __KrzyweLissajousaMyFrame1__
