#ifndef __KrzyweLissajousaMyFrame1__
#define __KrzyweLissajousaMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
// tutaj wpisujemy includy
#include <wx/dcclient.h>

/** Implementing MyFrame1 */
class KrzyweLissajousaMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void drawingPanel_onPaint( wxPaintEvent& event );
		void rotationX_Update( wxScrollEvent& event );
		void rotationY_Update( wxScrollEvent& event );
		void rotationZ_Update( wxScrollEvent& event );
		void sposobRysowania_update( wxCommandEvent& event );
		void coordinates_update( wxCommandEvent& event );
		void A_update( wxScrollEvent& event );
		void a_update( wxScrollEvent& event );
		void f_a_update( wxScrollEvent& event );
		void B_update( wxScrollEvent& event );
		void b_update( wxScrollEvent& event );
		void f_b_update( wxScrollEvent& event );
		void C_update( wxScrollEvent& event );
		void c_update( wxScrollEvent& event );
		void f_c_update( wxScrollEvent& event );
	public:
		/** Constructor */
		KrzyweLissajousaMyFrame1( wxWindow* parent );
	//// end generated class members
	// tutaj wpisujemy metody, zmienne, itp.

	private:
		/** _coordinates - zmienna(bool) wskazuj¹ca które wspó³rzêdne zosta³y wybrane przez u¿ytkownika.
		* == false(0) wspó³rzêdne (x,y, z)
		* == true(1) wspó³rzêdne (r, theta, phi)
		*/
		bool _coordinates;

		/** _drawingStyle - zmienna(bool) wskazuj¹ca sposób rysowania krzywych Lissajousa
		* == false(0) punkty
		* == true(1) odcinki
		*/
		bool _drawingStyle;




};

#endif // __KrzyweLissajousaMyFrame1__
