#ifndef __KrzyweLissajousaFrame__
#define __KrzyweLissajousaFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include "Matrix4d.h"
#include "Vector4d.h"
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>

/** Implementing Frame */
class KrzyweLissajousaFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void OnSizeChange( wxSizeEvent& event );
		void rotationX_Update( wxScrollEvent& event );
		void rotationY_Update( wxScrollEvent& event );
		void rotationZ_Update( wxScrollEvent& event );
		void sposobRysowania_update( wxCommandEvent& event );
		void coordinates_update( wxCommandEvent& event );
		void A_update( wxScrollEvent& event );
		void a_update( wxScrollEvent& event );
		void f_a_update( wxScrollEvent& event );
		void B_update( wxScrollEvent& event );
		void b_update( wxScrollEvent& event );
		void f_b_update( wxScrollEvent& event );
		void C_update( wxScrollEvent& event );
		void c_update( wxScrollEvent& event );
		void f_c_update( wxScrollEvent& event );
	public:
		/** Constructor */
		KrzyweLissajousaFrame( wxWindow* parent );
	//// end generated class members

		double functionX(double t) const;
		double functionY(double t) const;
		double functionZ(double t) const;

		void Repaint();
		~KrzyweLissajousaFrame();
	private:
		/** Zmienna(bool) wskazująca które współrzędne zostały wybrane przez użytkownika.
		* == false(0) współrzędne (x,y,z)
		* == true(1) współrzędne (r,theta,phi)
		*/
		bool _coordinates;

		/** Zmienna(bool) wskazująca sposób rysowania krzywych Lissajousa.
		* == false(0) punkty
		* == true(1) odcinki
		*/
		bool _drawingMethod;
		int _angleX;	/** Kąt obrotu wykresu względem osi OX. */
		int _angleY;	/** Kąt obrotu wykresu względem osi OY. */
		int _angleZ;	/** Kąt obrotu wykresu względem osi OZ. */

		double _ampX;	/** Amplituda funkcji x(t). */
		double _ampY;	/** Amplituda funkcji y(t). */
		double _ampZ;	/** Amplituda funkcji z(t). */
		int _aX;	/** a funkcji x(t). */
		int _bY;	/** b funkcji y(t). */
		int _cZ;	/** c funkcji z(t). */
		int _shiftX;	/** Przesunięcie funkcji x(t). */
		int _shiftY;	/** Przesunięcie funkcji y(t). */
		int _shiftZ;	/** Przesunięcie funkcji z(t). */

		const unsigned int _nodes = 200;	/** Liczba węzłów do narysowania. */
		/** Tablica przechowująca punkty.
		* _data_points[][0] - punkt x
		* _data_points[][1] - punkt y
		* _data_points[][2] - punkt z
		*/
		double(*_data_points)[3];
		/** Tablica przechowująca punkty początku i końców oś współrzędnych.
		* _axis_points[0][] - wspołrzędne punktu początkowego, przyjmującego najmniejszej wartości x, y, z
		* _axis_points[][0] - punkt x
		* _axis_points[][1] - punkt y
		* _axis_points[][2] - punkt z
		*/
		double _axis_points[4][3];







};

#endif // __KrzyweLissajousaFrame__