#ifndef __KrzyweLissajousaFrame__
#define __KrzyweLissajousaFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include "Matrix4d.h"
#include "Vector4d.h"
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

/** Implementing Frame */
class KrzyweLissajousaFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void drawingPanel_onPaint( wxPaintEvent& event );
		void rotationX_Update( wxScrollEvent& event );
		void rotationY_Update( wxScrollEvent& event );
		void rotationZ_Update( wxScrollEvent& event );
		void sposobRysowania_update( wxCommandEvent& event );
		void coordinates_update( wxCommandEvent& event );
		void A_update( wxScrollEvent& event );
		void a_update( wxScrollEvent& event );
		void f_a_update( wxScrollEvent& event );
		void B_update( wxScrollEvent& event );
		void b_update( wxScrollEvent& event );
		void f_b_update( wxScrollEvent& event );
		void C_update( wxScrollEvent& event );
		void c_update( wxScrollEvent& event );
		void f_c_update( wxScrollEvent& event );
	public:
		/** Constructor */
		KrzyweLissajousaFrame( wxWindow* parent );
	//// end generated class members
		double functionX(double t) const;
		double functionY(double t) const;
		double functionZ(double t) const;

		~KrzyweLissajousaFrame();
	private:
		/** Zmienna(bool) wskazuj¹ca które wspó³rzêdne zosta³y wybrane przez u¿ytkownika.
		* == false(0) wspó³rzêdne (x,y,z)
		* == true(1) wspó³rzêdne (r,theta,phi)
		*/
		bool _coordinates;

		/** Zmienna(bool) wskazuj³ca sposób rysowania krzywych Lissajousa
		* == false(0) punkty
		* == true(1) odcinki
		*/
		bool _drawingMethod;
		int _angleX;	/** K¹t obrotu wykresu wzglêdem osi OX */
		int _angleY;	/** K¹t obrotu wykresu wzglêdem osi OY */
		int _angleZ;		/** K¹t obrotu wykresu wzglêdem osi OZ */

		double _ampX;	/** Amplituda funkcji x(t)*/
		double _ampY;	/** Amplituda funkcji y(t)*/
		double _ampZ;	/** Amplituda funkcji z(t)*/
		int _aX;	/** a funkcji x(t)*/
		int _bY;	/** b funkcji y(t)*/
		int _cZ;	/** c funkcji z(t)*/
		int _shiftX;	/** przesuniêcie funkcji x(t) */
		int _shiftY;	/** przesuniêcie funkcji y(t) */
		int _shiftZ;	/** przesuniêcie funkcji z(t) */

		const unsigned int _nodes = 200;
		double(*_data_points)[3];






};

#endif // __KrzyweLissajousaFrame__
